### ISSUE TITLE
[MultiOS-USB] Bug: The file loopback.cfg contains outdated data

### ISSUE THREAD

**Issue by Mexit** [yledoare/ydfs#13]
It is not possible to boot the system from the ISO image.
https://github.com/yledoare/ydfs/blob/c28918df23a02923abf6c943c4d05d7c94c12166/2.10/boot-efi/boot/grub/loopback.cfg#L1-L16

**Comment by yledoare** [comment]
I never tried  grub/loopback.cfg
I think your are trying ISO from a custom Grub menu, could you share your grub Menuentry for starting LinuxConsole 2024 Iso ?

**Comment by yledoare** [comment]
Ok .. I will try to boot from your project : https://github.com/Mexit/MultiOS-USB

**Comment by yledoare** [comment]
But not sure it is an loopback.cfg issue
Ventoy did some hooks for LinuxConsole : 
https://github.com/ventoy/Ventoy/blob/master/IMG/cpio/ventoy/hook/debian/linuxconsole-disk.sh
https://github.com/ventoy/Ventoy/blob/master/IMG/cpio/ventoy/hook/debian/linuxconsole-hook.sh

**Comment by Mexit** [comment]
> But not sure it is an loopback.cfg issue

To be honest, I didn't check if everything works correctly with the proper content in the loopback.cfg file. I only noticed that the data there is outdated, and I reported it.

> Ok .. I will try to boot from your project : https://github.com/Mexit/MultiOS-USB

You can also check with your own configuration file, for example:
```
submenu "LinuxConsole" {
	iso_path="/path/to/iso"
	export iso_path
	loopback loop "$iso_path"
	root=(loop)
	configfile /boot/grub/loopback.cfg
}
```
or use other programs of this type (Super Grub2 Disk, ...)

> Ventoy did some hooks for LinuxConsole :

The loopback.cfg is there so that the system can be booted directly from the ISO without any additional modifications, using, for example, GRUB installed on the disk. If this is not intended, you can delete this file.

**Comment by yledoare** [comment]
Fixed : https://github.com/yledoare/ydfs/commit/ba3230ffd5b0f88845c8da968422db0cd39583b8

I Just had to write a correct loopback.cfg and mount iso from $isopath inside  my 2.10/init-x86/ydfs/detect/media script

You can test latest ISO here :  https://jukebox.linuxconsole.org/testing/linuxconsole.2024-09-20-x86_64.iso

**Comment by Mexit** [comment]
> You can test latest ISO here : https://jukebox.linuxconsole.org/testing/linuxconsole.2024-09-20-x86_64.iso

I tested the ISO, it boots up very quickly and smoothly. It also works on exFAT. Thanks!
