### ISSUE TITLE
Fast build from host : Error on kernel module

### ISSUE THREAD

**Issue by Boyquotes** [yledoare/ydfs#6]
When I build from host make iso, I have an error on iwlwifi but I don't find more detail than bellow. Can I found more information about this error ?

 Also I don't understand why the log display 6.0.11 for kernel version whereas the config.ini contain 6.1.23 ? 

`ydfs/kernel-x86_64/modules/6.0.11/linux-firmware/tdmb_nova_12mhz.inp
ydfs/kernel-x86_64/modules/6.0.11/linux-firmware/r8a779x_usb3_v3.dlmem
ydfs/kernel-x86_64/modules/6.0.11/linux-firmware/s5p-mfc-v7.fw
ydfs/kernel-x86_64/modules/6.0.11/linux-firmware/LICENSE.ice
ydfs/kernel-x86_64/modules/6.0.11/linux-firmware/iwlwifi-6000g2a-6.ucode
ydfs/kernel-x86_64/modules/6.0.11/linux-firmware/iwlwifi-so-a0-hr-b0-68.ucode
ydfs/kernel-x86_64/modules/6.0.11/linux-firmware/iwlwifi-3168-27.ucode
ydfs/kernel-x86_64/modules/6.0.11/linux-firmware/iwlwifi-cc-a0-73.ucode
ydfs/kernel-x86_64/modules/6.0.11/linux-firmware/hfi1_dc8051.fw
ydfs/kernel-x86_64/modules/6.0.11/linux-firmware/iwlwifi-Qu-b0-hr-b0-53.ucode
make: *** [Makefile:142: /root/ydfs/build/linux-x86_64-6.1.23/arch/x86_64/boot/bzImage] Error 1`

**Comment by yledoare** [comment]
The 6.0.11 files comes from the old fast archives (tag 2.9.4 / linuxconsole2022 ) : https://jukebox.linuxconsole.org/fast/old/
I just updated fast files for latest tag (2.9.6 / linuxconsole2023) : https://jukebox.linuxconsole.org/fast/

You can either change your config.ini, changing 6.0.11 to 6.1.23, or make new fresh build.

**Comment by Boyquotes** [comment]
Ok.

But when I `make clean` the 6.0.11 repository will not remove, it's a feature or an omission ?

`
~/ydfs-linux/2.9$ ls /home/debian/ydfs/kernel-x86_64/modules/
`
return
`
6.0.11
`

**Comment by yledoare** [comment]
Fixed on "make clean" : 

https://github.com/yledoare/ydfs/commit/9a982c605508a6fa0614196ec6ae2cfd1053571b

**Comment by yledoare** [comment]
Use last #[v2.10.1](https://github.com/yledoare/ydfs/releases/tag/v2.10.1) tag
